Feature/home activity
bakunovgerman/HomeWork_2_MTS pull request #3
Opened 2021-07-18 18:51 UTC by bakunovgerman

2021-07-20 08:17 UTC, maxlord requested changes

2021-07-20 08:17 UTC, maxlord commented on .idea/misc.xml
>  <?xml version="1.0" encoding="UTF-8"?>
Нужно добавить в .gitignore папку .idea

2021-07-20 08:17 UTC, maxlord commented on app/src/main/java/com/example/homework_2_mts/activities/HomeActivity.kt
> +        popularNowRecyclerViewAdapter.onPopularNowItemClick = { Toast.makeText(this, it.name, Toast.LENGTH_SHORT).show() }
Листенер можно передавать сразу в конструктор адаптера.
`PopularNowRecyclerViewAdapter(popularNowModel.getPopularNow()) { ... }`

2021-07-20 08:17 UTC, maxlord commented on app/src/main/java/com/example/homework_2_mts/adapters/MoviesRecyclerViewAdapter.kt
> +    var onMovieItemClick: ((MovieDto) -> Unit)? = null
Можно перенести в конструктор и сделать val, потому что врядли ты в процессе работы адаптера будешь ему кликеры добавлять/убирать/менять.

2021-07-20 08:17 UTC, maxlord commented on app/src/main/java/com/example/homework_2_mts/adapters/MoviesRecyclerViewAdapter.kt
> +            when(holder){
Обращай внимание на форматирование `){`. Хорошая практика, всегда форматить через хоткей `Ctrl + Alt + L`

2021-07-20 08:17 UTC, maxlord commented on app/src/main/java/com/example/homework_2_mts/adapters/MoviesViewHolder.kt
> +    public var movieItemRoot: ConstraintLayout? = null
все поля в Kotlin по-умолчанию public, поэтому нет необходимости это явно указывать.

2021-07-20 08:17 UTC, maxlord commented on app/src/main/java/com/example/homework_2_mts/adapters/MoviesViewHolder.kt
> +    private var moviePosterImg: ImageView? = null
Поля-виджеты нужно val-ами сделать. Да и вообще надо отдавать предпочтение val. Почитай про чистые функции. var надо использовать в исключительных случаях, когда нужно иметь возможность менять ссылку на объект в процессе работы.

2021-07-20 08:17 UTC, maxlord commented on app/src/main/java/com/example/homework_2_mts/adapters/MoviesViewHolder.kt
> +        movieRatingLayout?.numStars = 5
Это можно в разметке задать

2021-07-20 08:17 UTC, maxlord commented on app/src/main/res/values/strings.xml
> +    <string name="tv_popular_now_title_string">Популярное сейчас</string>
Префиксы вьюх не надо выносить в строки. Строки - это как справочник значений, там не должно быть деталей, где эта строка будет использоваться.

2021-07-20 11:42 UTC, bakunovgerman commented on .idea/misc.xml
>  <?xml version="1.0" encoding="UTF-8"?>
В .gitignore указан игнорировать .idea
Из репозитория удалить папку в ручную?

2021-07-20 11:52 UTC, bakunovgerman commented on app/src/main/java/com/example/homework_2_mts/adapters/MoviesRecyclerViewAdapter.kt
> +    var onMovieItemClick: ((MovieDto) -> Unit)? = null
В данном случае в HomeActivity не будет работать данный код:
        moviesRecyclerViewAdapter.onMovieItemClick = {
            Toast.makeText(this, it.title, Toast.LENGTH_SHORT).show()
        }
Ругается на val

2021-07-20 20:38 UTC, maxlord requested changes

2021-07-20 20:38 UTC, maxlord commented on .gitignore
> +/.idea
По идее должно хватать ./idea
Проверь, будет ли работать без указания остальных подпапок.
Можно еще посмотреть, как это делается для других папок, может можно использовать вилд-карды (*, **).

2021-07-20 20:38 UTC, maxlord commented on app/src/main/java/com/example/homework_2_mts/adapters/MoviesRecyclerViewAdapter.kt
> +class MoviesRecyclerViewAdapter (var list: List<MovieDto>, var onMovieItemClick: ((MovieDto) -> Unit))
Не совсем правильно, смотри как надо:
`
class MoviesRecyclerViewAdapter (var list: List<MovieDto>, val onMovieItemClick: ((MovieDto) -> Unit))
`
`
moviesRecyclerViewAdapter = MoviesRecyclerViewAdapter(moviesModel.getMovies()) {
    Toast.makeText(this, it.title, Toast.LENGTH_SHORT).show()
}
`

2021-07-20 20:45 UTC, maxlord requested changes

2021-07-20 20:45 UTC, maxlord commented on app/src/main/java/com/example/homework_2_mts/adapters/MoviesRecyclerViewAdapter.kt
> +                inflater.inflate(
В одну строку можно, у тебя скорей всего стоит в настройках 80 символов в строке, поставь 120. 
Форматировщик поэтому видимо у тебя так отформатил.

2021-07-20 20:45 UTC, maxlord commented on app/src/main/java/com/example/homework_2_mts/adapters/MoviesViewHolder.kt
> +        Picasso.get().load(movieDto.imageUrl).into(itemView.findViewById<ImageView>(R.id.movie_poster_img));
Вот тут не совсем верно переписал. 
Ты при каждом бинде щас будешь искать контролы, а ты должен их находить в init-блоке, как это было раньше.
Тогда они будут искаться только при созданию холдера.

2021-07-20 20:45 UTC, maxlord commented on app/src/main/java/com/example/homework_2_mts/adapters/PopularNowRecyclerViewAdapter.kt
> +        popularNowNameView?.setOnClickListener { onPopularNowItemClick?.invoke(list[position]) }
Это тоже можно вынести конструктор. Я обычно или айтем хранил в холдере, или в тег контрола писал айтем.
Ты сейчас при каждом бинде устанавливаешь листенер, а это оверхед, листенер должен быть один раз выставлен для контрола.

2021-07-20 20:45 UTC, maxlord commented on app/src/main/res/layout/activity_home.xml
> +                android:text="@string/tv_popular_now_title"
мы же обсудили, что `tv_` надо убрать

2021-07-21 14:40 UTC, bakunovgerman commented on .gitignore
> +/.idea
Оставил .idea/
На локальном репозитории выполнил команду: git rm -r --cached .idea

2021-07-21 14:51 UTC, bakunovgerman commented on app/src/main/java/com/example/homework_2_mts/adapters/MoviesRecyclerViewAdapter.kt
> +class MoviesRecyclerViewAdapter (var list: List<MovieDto>, var onMovieItemClick: ((MovieDto) -> Unit))
исправил

2021-07-21 15:02 UTC, bakunovgerman commented on app/src/main/java/com/example/homework_2_mts/adapters/MoviesRecyclerViewAdapter.kt
> +                inflater.inflate(
не помогло

2021-07-21 15:08 UTC, bakunovgerman commented on app/src/main/java/com/example/homework_2_mts/adapters/MoviesRecyclerViewAdapter.kt
> +                inflater.inflate(
исправил

2021-07-21 15:24 UTC, bakunovgerman commented on app/src/main/java/com/example/homework_2_mts/adapters/MoviesViewHolder.kt
> +        Picasso.get().load(movieDto.imageUrl).into(itemView.findViewById<ImageView>(R.id.movie_poster_img));
вывел в глобальные переменные val

2021-07-21 16:12 UTC, bakunovgerman commented on app/src/main/res/layout/activity_home.xml
> +                android:text="@string/tv_popular_now_title"
исправил

2021-07-22 08:12 UTC, bakunovgerman commented on app/src/main/java/com/example/homework_2_mts/adapters/PopularNowRecyclerViewAdapter.kt
> +        popularNowNameView?.setOnClickListener { onPopularNowItemClick?.invoke(list[position]) }
исправил

2021-07-24 11:26 UTC, merged