Feature/room
bakunovgerman/HomeWork_2_MTS pull request #7
Opened 2021-08-14 09:49 UTC by bakunovgerman

2021-08-14 22:41 UTC, maxlord requested changes

2021-08-14 22:41 UTC, maxlord commented on app/build.gradle
> +    def lifecycle_version = "2.3.1"
Все переменные надо вверху разместить в одном месте.

2021-08-14 22:41 UTC, maxlord commented on app/src/main/java/com/example/homework_2_mts/domain/MainFragmentViewModel.kt
> +                val movies = movieRepository.getMoviesDb()
getDbMovies()

2021-08-14 22:41 UTC, maxlord commented on app/src/main/java/com/example/homework_2_mts/domain/ProfileFragmentViewModel.kt
> +                throw AssertionError()
зочем?

2021-08-14 22:41 UTC, maxlord commented on app/src/main/java/com/example/homework_2_mts/presentation/activities/HomeActivity.kt
> +    companion object{
компаньон лучше перенести в конец класса

2021-08-14 22:41 UTC, maxlord commented on app/src/main/java/com/example/homework_2_mts/presentation/activities/HomeActivity.kt
> +                    if (navController.currentDestination?.id == R.id.movieDetailFragment ||
можно применять такую конструкцию
`if (... in listOf(id1, id2))`

2021-08-14 22:41 UTC, maxlord commented on app/src/main/java/com/example/homework_2_mts/presentation/activities/HomeActivity.kt
> +                    if (navController.currentDestination?.id == R.id.movieDetailFragment) {
Если переписать на when будет нагляднее и читаемее.

2021-08-14 22:41 UTC, maxlord commented on app/src/main/java/com/example/homework_2_mts/presentation/adapters/view_holders/MoviesSoonViewHolder.kt
> +class MoviesSoonViewHolder(view: View, onMovieItemClick: ((Movie) -> Unit)) :
внешние скобки для лямбды - лишние

2021-08-14 22:41 UTC, maxlord commented on app/src/main/java/com/example/homework_2_mts/presentation/adapters/view_holders/MoviesSoonViewHolder.kt
> +        tvMovieAge.text = String.format(movie.ageRestriction.toString() + '+')
надо вынести в строковый ресурс, что-то вроде:
`<string name="">%d+</string>`

2021-08-14 22:41 UTC, maxlord commented on app/src/main/java/com/example/homework_2_mts/presentation/fragments/MainFragment.kt
> +        init(view)
Нужно вызывать из onViewCreated()

2021-08-14 22:41 UTC, maxlord commented on app/src/main/java/com/example/homework_2_mts/presentation/fragments/MovieDetailFragment.kt
> +        tvMovieTitle.text = movie!!.title
А вдруг movie будет null?
Лучше вот так переписать:
`movie?.let { ... тут сеттим контролы ...  }`

2021-08-14 22:41 UTC, maxlord commented on app/src/main/java/com/example/homework_2_mts/presentation/fragments/ProfileFragment.kt
> +    private lateinit var nameEditText: EditText
etName и т.д.

2021-08-14 22:41 UTC, maxlord commented on app/src/main/java/com/example/homework_2_mts/presentation/fragments/ProfileFragment.kt
> +        inflater: LayoutInflater, container: ViewGroup?,
аргументы или в одну строку должны вмещаться, или каждый аргумент на новой строке.

2021-08-14 22:41 UTC, maxlord commented on app/src/main/java/com/example/homework_2_mts/presentation/fragments/ProfileFragment.kt
> +        initView(view)
Перенести в onViewCreated()

2021-08-14 22:41 UTC, maxlord commented on app/src/main/java/com/example/homework_2_mts/presentation/fragments/ProfileFragment.kt
> +        initRv(view)
initRecyclerView, тут лучше не сокращать.

2021-08-14 22:41 UTC, maxlord commented on app/src/main/java/com/example/homework_2_mts/presentation/fragments/ProfileFragment.kt
> +        val items = interestingUserModel.getPopularNow()
Надо получать данные из `ViewModel` через `LiveData`, потому что они могут измениться.
И данные должны загружаться из метода loadData(), т.е. эти вызовы нужно делать не в методе инициализации View.

2021-08-14 22:41 UTC, maxlord commented on app/src/main/java/com/example/homework_2_mts/presentation/fragments/ProfileFragment.kt
> +        val items = interestingUserModel.getPopularNow()
Т.е. важно отделять логику инициализации вьюх от загрузки данных в них.

2021-08-14 22:41 UTC, maxlord commented on app/src/main/java/com/example/homework_2_mts/presentation/fragments/ProfileFragment.kt
> +        else if (insertProfileState.exception != null)
Форматирование, если в if обрамляешь { }, не забывай делать то же самое и в else блоке.

2021-08-14 22:41 UTC, maxlord commented on app/src/main/java/com/example/homework_2_mts/presentation/fragments/ProfileFragment.kt
> +        if (profile != null){
Часто вижу отсутствие пробела между скобками.

2021-08-14 22:41 UTC, maxlord commented on app/src/main/java/com/example/homework_2_mts/repository/database/dao/MovieDao.kt
> +    @Query("DELETE from movies")
Ключевые слова рекомендуется писать в CAPS-стиле.

2021-08-14 22:41 UTC, maxlord commented on app/src/main/java/com/example/homework_2_mts/repository/database/entities/Movie.kt
> +data class Movie(
Называть лучше так: MovieEntity. 
Когда будет несколько слоев, куда надо будет прокидывать эти данные, будут несколько моделей: MovieEntity, MovieRemote, MovieItem  и т.д.

2021-08-14 22:41 UTC, maxlord commented on app/src/main/java/com/example/homework_2_mts/repository/repositories/MovieRepository.kt
> +        return getMoviesAPI() == getMoviesDb()
В проде нужно было бы придумать более простой способ проверки актуальности БД.
Как вариант хранить дату/время последнего обновления данных.

2021-08-14 22:41 UTC, maxlord commented on app/src/main/res/values/text_sizes.xml
>      <dimen name="movie_title">14sp</dimen>
Для размеров текста лучше дописывать в конце имени _text_size

2021-08-15 12:40 UTC, bakunovgerman commented on app/build.gradle
> +    def lifecycle_version = "2.3.1"
исправил

2021-08-15 12:44 UTC, bakunovgerman commented on app/src/main/java/com/example/homework_2_mts/domain/MainFragmentViewModel.kt
> +                val movies = movieRepository.getMoviesDb()
исправил

2021-08-15 12:45 UTC, bakunovgerman commented on app/src/main/java/com/example/homework_2_mts/domain/ProfileFragmentViewModel.kt
> +                throw AssertionError()
убрал

2021-08-15 12:48 UTC, bakunovgerman commented on app/src/main/java/com/example/homework_2_mts/presentation/activities/HomeActivity.kt
> +    companion object{
исправил

2021-08-15 13:06 UTC, bakunovgerman commented on app/src/main/java/com/example/homework_2_mts/presentation/fragments/ProfileFragment.kt
> +        if (profile != null){
исправил

2021-08-15 13:21 UTC, bakunovgerman commented on app/src/main/java/com/example/homework_2_mts/repository/database/dao/MovieDao.kt
> +    @Query("DELETE from movies")
исправил

2021-08-15 13:39 UTC, bakunovgerman commented on app/src/main/java/com/example/homework_2_mts/repository/database/entities/Movie.kt
> +data class Movie(
исправил

2021-08-17 14:59 UTC, bakunovgerman commented on app/src/main/java/com/example/homework_2_mts/repository/repositories/MovieRepository.kt
> +        return getMoviesAPI() == getMoviesDb()
выполнено

2021-08-18 14:40 UTC, maxlord requested changes

2021-08-18 14:40 UTC, maxlord commented on app/src/main/java/com/example/homework_2_mts/presentation/adapters/MoviesAdapter.kt
> +            //notifyDataSetChanged()
А нотифай где вызывается?

2021-08-18 14:40 UTC, maxlord commented on app/src/main/java/com/example/homework_2_mts/presentation/adapters/MoviesAdapter.kt
> +            items.clear()
Лучше в любом случае чистить айтемы, а по условию добавлять.

2021-08-18 14:40 UTC, maxlord commented on app/src/main/java/com/example/homework_2_mts/presentation/fragments/MainFragment.kt
> +        swipeRefresh = view.findViewById(R.id.swipe_refresh)
Работу с вьюшками переносим в onViewCreated()

2021-08-19 10:23 UTC, maxlord approved these changes

2021-08-19 14:14 UTC, merged